In [1]:
#Importation du pandas
import pandas as pd

In [2]:
df=pd.read_csv('Stg_Vente_520_enregistrements.csv')

In [3]:
#Afficher les 5 premières lignes
df.head()

,ID_VENTE,CODE_PRODUIT,PRODUIT,CATEGORIE,QUANTITE,PRIX_UNITAIRE,MONTANT,DATE_VENTE,POINT_VENTE,VILLE,CODE_CLIENT,TYPE_CLIENT,SEGMENT
0,1,P001,Huile Dinor 5L,Hygiène,2.0,2000.0,4000.0,2026-01-01,Magasin Conakry Centre,Kindia,C001,Détaillant,Standard
1,2,P002,Savon Palmex 250g,Boissons,3.0,3000.0,9000.0,2026-02-02,Magasin Kindia,Labé,C002,Grossiste,Premium
2,3,P003,Riz local 25kg,Confiserie,4.0,4000.0,16000.0,2026-03-03,Magasin Boké,Kankan,C003,Détaillant,Standard
3,4,P004,Lait en poudre 400g,Alimentation,5.0,5000.0,25000.0,2026-04-04,Magasin Mamou,Mamou,C004,Grossiste,Premium
4,5,P005,Sucre cristal 1kg,Hygiène,6.0,6000.0,36000.0,2026-05-05,Magasin Labé,Boké,C005,Détaillant,Standard

In [8]:
df.dtypes

ID_VENTE           int64
CODE_PRODUIT      object
PRODUIT           object
CATEGORIE         object
QUANTITE         float64
PRIX_UNITAIRE    float64
MONTANT          float64
DATE_VENTE        object
POINT_VENTE       object
VILLE             object
CODE_CLIENT       object
TYPE_CLIENT       object
SEGMENT           object
dtype: object

In [9]:
df.isnull().sum()

ID_VENTE          0
CODE_PRODUIT     10
PRODUIT          10
CATEGORIE        10
QUANTITE         10
PRIX_UNITAIRE    10
MONTANT          10
DATE_VENTE        0
POINT_VENTE      10
VILLE             0
CODE_CLIENT      10
TYPE_CLIENT      10
SEGMENT          10
dtype: int64

In [10]:
df.describe()

         ID_VENTE    QUANTITE  PRIX_UNITAIRE       MONTANT
count  520.000000  510.000000     510.000000  5.100000e+02
mean   250.692308   42.556863   10240.196078  4.481353e+05
std    149.934287   29.987877    5649.699816  4.446918e+05
min      1.000000  -30.000000    1000.000000 -1.600000e+05
25%    120.750000   16.000000    5000.000000  8.100000e+04
50%    250.500000   40.000000   10000.000000  3.150000e+05
75%    380.250000   67.750000   15000.000000  7.035000e+05
max    510.000000   99.000000   20000.000000  1.881000e+06